<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {        
        DB::table('countries')->truncate();

    	$Countries = [
    		array('id' => '1','sortname' => 'AF','country_name' => 'Afghanistan','country_lat' => '33','country_lng' => '65','timezone' => 'Asia/Kabul'),
    		array('id' => '2','sortname' => 'AL','country_name' => 'Albania','country_lat' => '41','country_lng' => '20','timezone' => 'Europe/Tirane'),
    		array('id' => '3','sortname' => 'DZ','country_name' => 'Algeria','country_lat' => '28','country_lng' => '3','timezone' => 'Africa/Algiers'),
    		array('id' => '4','sortname' => 'AS','country_name' => 'American Samoa','country_lat' => '-14.33333333','country_lng' => '-170','timezone' => 'Pacific/Pago_Pago'),
    		array('id' => '5','sortname' => 'AD','country_name' => 'Andorra','country_lat' => '42.5','country_lng' => '1.5','timezone' => 'Europe/Andorra'),
    		array('id' => '6','sortname' => 'AO','country_name' => 'Angola','country_lat' => '-12.5','country_lng' => '18.5','timezone' => 'Africa/Luanda'),
    		array('id' => '7','sortname' => 'AI','country_name' => 'Anguilla','country_lat' => '18.25','country_lng' => '-63.16666666','timezone' => 'America/Anguilla'),
    		array('id' => '8','sortname' => 'AQ','country_name' => 'Antarctica','country_lat' => '-90','country_lng' => '0','timezone' => 'Antarctica/McMurdo'),
    		array('id' => '9','sortname' => 'AG','country_name' => 'Antigua And Barbuda','country_lat' => '17.05','country_lng' => '-61.8','timezone' => 'America/Antigua'),
    		array('id' => '10','sortname' => 'AR','country_name' => 'Argentina','country_lat' => '-34','country_lng' => '-64','timezone' => 'America/Argentina/Buenos_Aires'),
    		array('id' => '11','sortname' => 'AM','country_name' => 'Armenia','country_lat' => '40','country_lng' => '45','timezone' => 'Asia/Yerevan'),
    		array('id' => '12','sortname' => 'AW','country_name' => 'Aruba','country_lat' => '12.5','country_lng' => '-69.96666666','timezone' => 'America/Aruba'),
    		array('id' => '13','sortname' => 'AU','country_name' => 'Australia','country_lat' => '-27','country_lng' => '133','timezone' => 'Australia/Lord_Howe'),
    		array('id' => '14','sortname' => 'AT','country_name' => 'Austria','country_lat' => '47.33333333','country_lng' => '13.33333333','timezone' => 'Europe/Vienna'),
    		array('id' => '15','sortname' => 'AZ','country_name' => 'Azerbaijan','country_lat' => '40.5','country_lng' => '47.5','timezone' => 'Asia/Baku'),
    		array('id' => '16','sortname' => 'BS','country_name' => 'Bahamas The','country_lat' => '24.25','country_lng' => '-76','timezone' => 'America/Nassau'),
    		array('id' => '17','sortname' => 'BH','country_name' => 'Bahrain','country_lat' => '26','country_lng' => '50.55','timezone' => 'Asia/Bahrain'),
    		array('id' => '18','sortname' => 'BD','country_name' => 'Bangladesh','country_lat' => '24','country_lng' => '90','timezone' => 'Asia/Dhaka'),
    		array('id' => '19','sortname' => 'BB','country_name' => 'Barbados','country_lat' => '13.16666666','country_lng' => '-59.53333333','timezone' => 'America/Barbados'),
    		array('id' => '20','sortname' => 'BY','country_name' => 'Belarus','country_lat' => '53','country_lng' => '28','timezone' => 'Europe/Minsk'),
    		array('id' => '21','sortname' => 'BE','country_name' => 'Belgium','country_lat' => '50.83333333','country_lng' => '4','timezone' => 'Europe/Brussels'),
    		array('id' => '22','sortname' => 'BZ','country_name' => 'Belize','country_lat' => '17.25','country_lng' => '-88.75','timezone' => 'America/Belize'),
    		array('id' => '23','sortname' => 'BJ','country_name' => 'Benin','country_lat' => '9.5','country_lng' => '2.25','timezone' => 'Africa/Porto-Novo'),
    		array('id' => '24','sortname' => 'BM','country_name' => 'Bermuda','country_lat' => '32.33333333','country_lng' => '-64.75','timezone' => 'Atlantic/Bermuda'),
    		array('id' => '25','sortname' => 'BT','country_name' => 'Bhutan','country_lat' => '27.5','country_lng' => '90.5','timezone' => 'Asia/Thimphu'),
    		array('id' => '26','sortname' => 'BO','country_name' => 'Bolivia','country_lat' => '-17','country_lng' => '-65','timezone' => 'America/La_Paz'),
    		array('id' => '27','sortname' => 'BA','country_name' => 'Bosnia and Herzegovina','country_lat' => '44','country_lng' => '18','timezone' => 'Europe/Sarajevo'),
    		array('id' => '28','sortname' => 'BW','country_name' => 'Botswana','country_lat' => '-22','country_lng' => '24','timezone' => 'Africa/Gaborone'),
    		array('id' => '29','sortname' => 'BV','country_name' => 'Bouvet Island','country_lat' => '-54.43333333','country_lng' => '3.4','timezone' => 'Europe/Oslo'),
    		array('id' => '30','sortname' => 'BR','country_name' => 'Brazil','country_lat' => '-10','country_lng' => '-55','timezone' => 'America/Noronha'),
    		array('id' => '31','sortname' => 'IO','country_name' => 'British Indian Ocean Territory','country_lat' => '-6','country_lng' => '71.5','timezone' => 'Indian/Chagos'),
    		array('id' => '32','sortname' => 'BN','country_name' => 'Brunei','country_lat' => '4.5','country_lng' => '114.66666666','timezone' => 'Asia/Brunei'),
    		array('id' => '33','sortname' => 'BG','country_name' => 'Bulgaria','country_lat' => '43','country_lng' => '25','timezone' => 'Europe/Sofia'),
    		array('id' => '34','sortname' => 'BF','country_name' => 'Burkina Faso','country_lat' => '13','country_lng' => '-2','timezone' => 'Africa/Ouagadougou'),
    		array('id' => '35','sortname' => 'BI','country_name' => 'Burundi','country_lat' => '-3.5','country_lng' => '30','timezone' => 'Africa/Bujumbura'),
    		array('id' => '36','sortname' => 'KH','country_name' => 'Cambodia','country_lat' => '13','country_lng' => '105','timezone' => 'Asia/Phnom_Penh'),
    		array('id' => '37','sortname' => 'CM','country_name' => 'Cameroon','country_lat' => '6','country_lng' => '12','timezone' => 'Africa/Douala'),
    		array('id' => '38','sortname' => 'CA','country_name' => 'Canada','country_lat' => '60','country_lng' => '-95','timezone' => 'America/St_Johns'),
    		array('id' => '39','sortname' => 'CV','country_name' => 'Cape Verde','country_lat' => '16','country_lng' => '-24','timezone' => 'Atlantic/Cape_Verde'),
    		array('id' => '40','sortname' => 'KY','country_name' => 'Cayman Islands','country_lat' => '19.5','country_lng' => '-80.5','timezone' => 'America/Cayman'),
    		array('id' => '41','sortname' => 'CF','country_name' => 'Central African Republic','country_lat' => '7','country_lng' => '21','timezone' => 'Africa/Bangui'),
    		array('id' => '42','sortname' => 'TD','country_name' => 'Chad','country_lat' => '15','country_lng' => '19','timezone' => 'Africa/Ndjamena'),
    		array('id' => '43','sortname' => 'CL','country_name' => 'Chile','country_lat' => '-30','country_lng' => '-71','timezone' => 'America/Santiago'),
    		array('id' => '44','sortname' => 'CN','country_name' => 'China','country_lat' => '35','country_lng' => '105','timezone' => 'Asia/Shanghai'),
    		array('id' => '45','sortname' => 'CX','country_name' => 'Christmas Island','country_lat' => '-10.5','country_lng' => '105.66666666','timezone' => 'Indian/Christmas'),
    		array('id' => '46','sortname' => 'CC','country_name' => 'Cocos (Keeling) Islands','country_lat' => '-12.5','country_lng' => '96.83333333','timezone' => 'Indian/Cocos'),
    		array('id' => '47','sortname' => 'CO','country_name' => 'Colombia','country_lat' => '4','country_lng' => '-72','timezone' => 'America/Bogota'),
    		array('id' => '48','sortname' => 'KM','country_name' => 'Comoros','country_lat' => '-12.16666666','country_lng' => '44.25','timezone' => 'Indian/Comoro'),
    		array('id' => '49','sortname' => 'CG','country_name' => 'Congo','country_lat' => '-1','country_lng' => '15','timezone' => 'Africa/Brazzaville'),
    		array('id' => '50','sortname' => 'CD','country_name' => 'Congo The Democratic Republic Of The','country_lat' => '0','country_lng' => '25','timezone' => 'Africa/Kinshasa'),
    		array('id' => '51','sortname' => 'CK','country_name' => 'Cook Islands','country_lat' => '-21.23333333','country_lng' => '-159.76666666','timezone' => 'Pacific/Rarotonga'),
    		array('id' => '52','sortname' => 'CR','country_name' => 'Costa Rica','country_lat' => '10','country_lng' => '-84','timezone' => 'America/Costa_Rica'),
    		array('id' => '53','sortname' => 'CI','country_name' => 'Cote D\'Ivoire (Ivory Coast)','country_lat' => '8','country_lng' => '-5','timezone' => 'Africa/Abidjan'),
    		array('id' => '54','sortname' => 'HR','country_name' => 'Croatia (Hrvatska)','country_lat' => '45.16666666','country_lng' => '15.5','timezone' => 'Europe/Zagreb'),
    		array('id' => '55','sortname' => 'CU','country_name' => 'Cuba','country_lat' => '21.5','country_lng' => '-80','timezone' => 'America/Havana'),
    		array('id' => '56','sortname' => 'CY','country_name' => 'Cyprus','country_lat' => '35','country_lng' => '33','timezone' => 'Asia/Nicosia'),
    		array('id' => '57','sortname' => 'CZ','country_name' => 'Czech Republic','country_lat' => '49.75','country_lng' => '15.5','timezone' => 'Europe/Prague'),
    		array('id' => '58','sortname' => 'DK','country_name' => 'Denmark','country_lat' => '56','country_lng' => '10','timezone' => 'Europe/Copenhagen'),
    		array('id' => '59','sortname' => 'DJ','country_name' => 'Djibouti','country_lat' => '11.5','country_lng' => '43','timezone' => 'Africa/Djibouti'),
    		array('id' => '60','sortname' => 'DM','country_name' => 'Dominica','country_lat' => '15.41666666','country_lng' => '-61.33333333','timezone' => 'America/Dominica'),
    		array('id' => '61','sortname' => 'DO','country_name' => 'Dominican Republic','country_lat' => '19','country_lng' => '-70.66666666','timezone' => 'America/Santo_Domingo'),
    		array('id' => '62','sortname' => 'TL','country_name' => 'East Timor','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '63','sortname' => 'EC','country_name' => 'Ecuador','country_lat' => '-2','country_lng' => '-77.5','timezone' => 'America/Guayaquil'),
    		array('id' => '64','sortname' => 'EG','country_name' => 'Egypt','country_lat' => '27','country_lng' => '30','timezone' => 'Africa/Cairo'),
    		array('id' => '65','sortname' => 'SV','country_name' => 'El Salvador','country_lat' => '13.83333333','country_lng' => '-88.91666666','timezone' => 'America/El_Salvador'),
    		array('id' => '66','sortname' => 'GQ','country_name' => 'Equatorial Guinea','country_lat' => '2','country_lng' => '10','timezone' => 'Africa/Malabo'),
    		array('id' => '67','sortname' => 'ER','country_name' => 'Eritrea','country_lat' => '15','country_lng' => '39','timezone' => 'Africa/Asmara'),
    		array('id' => '68','sortname' => 'EE','country_name' => 'Estonia','country_lat' => '59','country_lng' => '26','timezone' => 'Europe/Tallinn'),
    		array('id' => '69','sortname' => 'ET','country_name' => 'Ethiopia','country_lat' => '8','country_lng' => '38','timezone' => 'Africa/Addis_Ababa'),
    		array('id' => '70','sortname' => 'XA','country_name' => 'External Territories of Australia','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '71','sortname' => 'FK','country_name' => 'Falkland Islands','country_lat' => '-51.75','country_lng' => '-59','timezone' => 'Atlantic/Stanley'),
    		array('id' => '72','sortname' => 'FO','country_name' => 'Faroe Islands','country_lat' => '62','country_lng' => '-7','timezone' => 'Atlantic/Faroe'),
    		array('id' => '73','sortname' => 'FJ','country_name' => 'Fiji Islands','country_lat' => '-18','country_lng' => '175','timezone' => 'Pacific/Fiji'),
    		array('id' => '74','sortname' => 'FI','country_name' => 'Finland','country_lat' => '64','country_lng' => '26','timezone' => 'Europe/Helsinki'),
    		array('id' => '75','sortname' => 'FR','country_name' => 'France','country_lat' => '46','country_lng' => '2','timezone' => 'Europe/Paris'),
    		array('id' => '76','sortname' => 'GF','country_name' => 'French Guiana','country_lat' => '4','country_lng' => '-53','timezone' => 'America/Cayenne'),
    		array('id' => '77','sortname' => 'PF','country_name' => 'French Polynesia','country_lat' => '-15','country_lng' => '-140','timezone' => 'Pacific/Tahiti'),
    		array('id' => '78','sortname' => 'TF','country_name' => 'French Southern Territories','country_lat' => '-49.25','country_lng' => '69.167','timezone' => 'Indian/Kerguelen'),
    		array('id' => '79','sortname' => 'GA','country_name' => 'Gabon','country_lat' => '-1','country_lng' => '11.75','timezone' => 'Africa/Libreville'),
    		array('id' => '80','sortname' => 'GM','country_name' => 'Gambia The','country_lat' => '13.46666666','country_lng' => '-16.56666666','timezone' => 'Africa/Banjul'),
    		array('id' => '81','sortname' => 'GE','country_name' => 'Georgia','country_lat' => '42','country_lng' => '43.5','timezone' => 'Asia/Tbilisi'),
    		array('id' => '82','sortname' => 'DE','country_name' => 'Germany','country_lat' => '51','country_lng' => '9','timezone' => 'Europe/Berlin'),
    		array('id' => '83','sortname' => 'GH','country_name' => 'Ghana','country_lat' => '8','country_lng' => '-2','timezone' => 'Africa/Accra'),
    		array('id' => '84','sortname' => 'GI','country_name' => 'Gibraltar','country_lat' => '36.13333333','country_lng' => '-5.35','timezone' => 'Europe/Gibraltar'),
    		array('id' => '85','sortname' => 'GR','country_name' => 'Greece','country_lat' => '39','country_lng' => '22','timezone' => 'Europe/Athens'),
    		array('id' => '86','sortname' => 'GL','country_name' => 'Greenland','country_lat' => '72','country_lng' => '-40','timezone' => 'America/Godthab'),
    		array('id' => '87','sortname' => 'GD','country_name' => 'Grenada','country_lat' => '12.11666666','country_lng' => '-61.66666666','timezone' => 'America/Grenada'),
    		array('id' => '88','sortname' => 'GP','country_name' => 'Guadeloupe','country_lat' => '16.25','country_lng' => '-61.583333','timezone' => 'America/Guadeloupe'),
    		array('id' => '89','sortname' => 'GU','country_name' => 'Guam','country_lat' => '13.46666666','country_lng' => '144.78333333','timezone' => 'Pacific/Guam'),
    		array('id' => '90','sortname' => 'GT','country_name' => 'Guatemala','country_lat' => '15.5','country_lng' => '-90.25','timezone' => 'America/Guatemala'),
    		array('id' => '91','sortname' => 'GG','country_name' => 'Guernsey and Alderney','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '92','sortname' => 'GN','country_name' => 'Guinea','country_lat' => '11','country_lng' => '-10','timezone' => 'Africa/Conakry'),
    		array('id' => '93','sortname' => 'GW','country_name' => 'Guinea-Bissau','country_lat' => '12','country_lng' => '-15','timezone' => 'Africa/Bissau'),
    		array('id' => '94','sortname' => 'GY','country_name' => 'Guyana','country_lat' => '5','country_lng' => '-59','timezone' => 'America/Guyana'),
    		array('id' => '95','sortname' => 'HT','country_name' => 'Haiti','country_lat' => '19','country_lng' => '-72.41666666','timezone' => 'America/Port-au-Prince'),
    		array('id' => '96','sortname' => 'HM','country_name' => 'Heard and McDonald Islands','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '97','sortname' => 'HN','country_name' => 'Honduras','country_lat' => '15','country_lng' => '-86.5','timezone' => 'America/Tegucigalpa'),
    		array('id' => '98','sortname' => 'HK','country_name' => 'Hong Kong S.A.R.','country_lat' => '22.267','country_lng' => '114.188','timezone' => 'Asia/Hong_Kong'),
    		array('id' => '99','sortname' => 'HU','country_name' => 'Hungary','country_lat' => '47','country_lng' => '20','timezone' => 'Europe/Budapest'),
    		array('id' => '100','sortname' => 'IS','country_name' => 'Iceland','country_lat' => '65','country_lng' => '-18','timezone' => 'Atlantic/Reykjavik'),
    		array('id' => '101','sortname' => 'IN','country_name' => 'India','country_lat' => '20','country_lng' => '77','timezone' => 'Asia/Kolkata'),
    		array('id' => '102','sortname' => 'ID','country_name' => 'Indonesia','country_lat' => '-5','country_lng' => '120','timezone' => 'Asia/Jakarta'),
    		array('id' => '103','sortname' => 'IR','country_name' => 'Iran','country_lat' => '32','country_lng' => '53','timezone' => 'Asia/Tehran'),
    		array('id' => '104','sortname' => 'IQ','country_name' => 'Iraq','country_lat' => '33','country_lng' => '44','timezone' => 'Asia/Baghdad'),
    		array('id' => '105','sortname' => 'IE','country_name' => 'Ireland','country_lat' => '53','country_lng' => '-8','timezone' => 'Europe/Dublin'),
    		array('id' => '106','sortname' => 'IL','country_name' => 'Israel','country_lat' => '31.47','country_lng' => '35.13','timezone' => 'Asia/Jerusalem'),
    		array('id' => '107','sortname' => 'IT','country_name' => 'Italy','country_lat' => '42.83333333','country_lng' => '12.83333333','timezone' => 'Europe/Rome'),
    		array('id' => '108','sortname' => 'JM','country_name' => 'Jamaica','country_lat' => '18.25','country_lng' => '-77.5','timezone' => 'America/Jamaica'),
    		array('id' => '109','sortname' => 'JP','country_name' => 'Japan','country_lat' => '36','country_lng' => '138','timezone' => 'Asia/Tokyo'),
    		array('id' => '110','sortname' => 'JE','country_name' => 'Jersey','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '111','sortname' => 'JO','country_name' => 'Jordan','country_lat' => '31','country_lng' => '36','timezone' => 'Asia/Amman'),
    		array('id' => '112','sortname' => 'KZ','country_name' => 'Kazakhstan','country_lat' => '48','country_lng' => '68','timezone' => 'Asia/Almaty'),
    		array('id' => '113','sortname' => 'KE','country_name' => 'Kenya','country_lat' => '1','country_lng' => '38','timezone' => 'Africa/Nairobi'),
    		array('id' => '114','sortname' => 'KI','country_name' => 'Kiribati','country_lat' => '1.41666666','country_lng' => '173','timezone' => 'Pacific/Tarawa'),
    		array('id' => '115','sortname' => 'KP','country_name' => 'Korea North','country_lat' => '40','country_lng' => '127','timezone' => 'Asia/Pyongyang'),
    		array('id' => '116','sortname' => 'KR','country_name' => 'Korea South','country_lat' => '37','country_lng' => '127.5','timezone' => 'Asia/Seoul'),
    		array('id' => '117','sortname' => 'KW','country_name' => 'Kuwait','country_lat' => '29.5','country_lng' => '45.75','timezone' => 'Asia/Kuwait'),
    		array('id' => '118','sortname' => 'KG','country_name' => 'Kyrgyzstan','country_lat' => '41','country_lng' => '75','timezone' => 'Asia/Bishkek'),
    		array('id' => '119','sortname' => 'LA','country_name' => 'Laos','country_lat' => '18','country_lng' => '105','timezone' => 'Asia/Vientiane'),
    		array('id' => '120','sortname' => 'LV','country_name' => 'Latvia','country_lat' => '57','country_lng' => '25','timezone' => 'Europe/Riga'),
    		array('id' => '121','sortname' => 'LB','country_name' => 'Lebanon','country_lat' => '33.83333333','country_lng' => '35.83333333','timezone' => 'Asia/Beirut'),
    		array('id' => '122','sortname' => 'LS','country_name' => 'Lesotho','country_lat' => '-29.5','country_lng' => '28.5','timezone' => 'Africa/Maseru'),
    		array('id' => '123','sortname' => 'LR','country_name' => 'Liberia','country_lat' => '6.5','country_lng' => '-9.5','timezone' => 'Africa/Monrovia'),
    		array('id' => '124','sortname' => 'LY','country_name' => 'Libya','country_lat' => '25','country_lng' => '17','timezone' => 'Africa/Tripoli'),
    		array('id' => '125','sortname' => 'LI','country_name' => 'Liechtenstein','country_lat' => '47.26666666','country_lng' => '9.53333333','timezone' => 'Europe/Vaduz'),
    		array('id' => '126','sortname' => 'LT','country_name' => 'Lithuania','country_lat' => '56','country_lng' => '24','timezone' => 'Europe/Vilnius'),
    		array('id' => '127','sortname' => 'LU','country_name' => 'Luxembourg','country_lat' => '49.75','country_lng' => '6.16666666','timezone' => 'Europe/Luxembourg'),
    		array('id' => '128','sortname' => 'MO','country_name' => 'Macau S.A.R.','country_lat' => '22.16666666','country_lng' => '113.55','timezone' => 'Asia/Macau'),
    		array('id' => '129','sortname' => 'MK','country_name' => 'Macedonia','country_lat' => '41.83333333','country_lng' => '22','timezone' => 'Europe/Skopje'),
    		array('id' => '130','sortname' => 'MG','country_name' => 'Madagascar','country_lat' => '-20','country_lng' => '47','timezone' => 'Indian/Antananarivo'),
    		array('id' => '131','sortname' => 'MW','country_name' => 'Malawi','country_lat' => '-13.5','country_lng' => '34','timezone' => 'Africa/Blantyre'),
    		array('id' => '132','sortname' => 'MY','country_name' => 'Malaysia','country_lat' => '2.5','country_lng' => '112.5','timezone' => 'Asia/Kuala_Lumpur'),
    		array('id' => '133','sortname' => 'MV','country_name' => 'Maldives','country_lat' => '3.25','country_lng' => '73','timezone' => 'Indian/Maldives'),
    		array('id' => '134','sortname' => 'ML','country_name' => 'Mali','country_lat' => '17','country_lng' => '-4','timezone' => 'Africa/Bamako'),
    		array('id' => '135','sortname' => 'MT','country_name' => 'Malta','country_lat' => '35.83333333','country_lng' => '14.58333333','timezone' => 'Europe/Malta'),
    		array('id' => '136','sortname' => 'IMN','country_name' => 'Man (Isle of)','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '137','sortname' => 'MH','country_name' => 'Marshall Islands','country_lat' => '9','country_lng' => '168','timezone' => 'Pacific/Majuro'),
    		array('id' => '138','sortname' => 'MQ','country_name' => 'Martinique','country_lat' => '14.666667','country_lng' => '-61','timezone' => 'America/Martinique'),
    		array('id' => '139','sortname' => 'MR','country_name' => 'Mauritania','country_lat' => '20','country_lng' => '-12','timezone' => 'Africa/Nouakchott'),
    		array('id' => '140','sortname' => 'MU','country_name' => 'Mauritius','country_lat' => '-20.28333333','country_lng' => '57.55','timezone' => 'Indian/Mauritius'),
    		array('id' => '141','sortname' => 'YT','country_name' => 'Mayotte','country_lat' => '-12.83333333','country_lng' => '45.16666666','timezone' => 'Indian/Mayotte'),
    		array('id' => '142','sortname' => 'MX','country_name' => 'Mexico','country_lat' => '23','country_lng' => '-102','timezone' => 'America/Mexico_City'),
    		array('id' => '143','sortname' => 'FM','country_name' => 'Micronesia','country_lat' => '6.91666666','country_lng' => '158.25','timezone' => 'Pacific/Chuuk'),
    		array('id' => '144','sortname' => 'MD','country_name' => 'Moldova','country_lat' => '47','country_lng' => '29','timezone' => 'Europe/Chisinau'),
    		array('id' => '145','sortname' => 'MC','country_name' => 'Monaco','country_lat' => '43.73333333','country_lng' => '7.4','timezone' => 'Europe/Monaco'),
    		array('id' => '146','sortname' => 'MN','country_name' => 'Mongolia','country_lat' => '46','country_lng' => '105','timezone' => 'Asia/Ulaanbaatar'),
    		array('id' => '147','sortname' => 'MS','country_name' => 'Montserrat','country_lat' => '16.75','country_lng' => '-62.2','timezone' => 'America/Montserrat'),
    		array('id' => '148','sortname' => 'MA','country_name' => 'Morocco','country_lat' => '32','country_lng' => '-5','timezone' => 'Africa/Casablanca'),
    		array('id' => '149','sortname' => 'MZ','country_name' => 'Mozambique','country_lat' => '-18.25','country_lng' => '35','timezone' => 'Africa/Maputo'),
    		array('id' => '150','sortname' => 'MM','country_name' => 'Myanmar','country_lat' => '22','country_lng' => '98','timezone' => 'Asia/Rangoon'),
    		array('id' => '151','sortname' => 'NA','country_name' => 'Namibia','country_lat' => '-22','country_lng' => '17','timezone' => 'Africa/Windhoek'),
    		array('id' => '152','sortname' => 'NR','country_name' => 'Nauru','country_lat' => '-0.53333333','country_lng' => '166.91666666','timezone' => 'Pacific/Nauru'),
    		array('id' => '153','sortname' => 'NP','country_name' => 'Nepal','country_lat' => '28','country_lng' => '84','timezone' => 'Asia/Kathmandu'),
    		array('id' => '154','sortname' => 'AN','country_name' => 'Netherlands Antilles','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '155','sortname' => 'NL','country_name' => 'Netherlands The','country_lat' => '52.5','country_lng' => '5.75','timezone' => 'Europe/Amsterdam'),
    		array('id' => '156','sortname' => 'NC','country_name' => 'New Caledonia','country_lat' => '-21.5','country_lng' => '165.5','timezone' => 'Pacific/Noumea'),
    		array('id' => '157','sortname' => 'NZ','country_name' => 'New Zealand','country_lat' => '-41','country_lng' => '174','timezone' => 'Pacific/Auckland'),
    		array('id' => '158','sortname' => 'NI','country_name' => 'Nicaragua','country_lat' => '13','country_lng' => '-85','timezone' => 'America/Managua'),
    		array('id' => '159','sortname' => 'NE','country_name' => 'Niger','country_lat' => '16','country_lng' => '8','timezone' => 'Africa/Niamey'),
    		array('id' => '160','sortname' => 'NG','country_name' => 'Nigeria','country_lat' => '10','country_lng' => '8','timezone' => 'Africa/Lagos'),
    		array('id' => '161','sortname' => 'NU','country_name' => 'Niue','country_lat' => '-19.03333333','country_lng' => '-169.86666666','timezone' => 'Pacific/Niue'),
    		array('id' => '162','sortname' => 'NF','country_name' => 'Norfolk Island','country_lat' => '-29.03333333','country_lng' => '167.95','timezone' => 'Pacific/Norfolk'),
    		array('id' => '163','sortname' => 'MP','country_name' => 'Northern Mariana Islands','country_lat' => '15.2','country_lng' => '145.75','timezone' => 'Pacific/Saipan'),
    		array('id' => '164','sortname' => 'NO','country_name' => 'Norway','country_lat' => '62','country_lng' => '10','timezone' => 'Europe/Oslo'),
    		array('id' => '165','sortname' => 'OM','country_name' => 'Oman','country_lat' => '21','country_lng' => '57','timezone' => 'Asia/Muscat'),
    		array('id' => '166','sortname' => 'PK','country_name' => 'Pakistan','country_lat' => '30','country_lng' => '70','timezone' => 'Asia/Karachi'),
    		array('id' => '167','sortname' => 'PW','country_name' => 'Palau','country_lat' => '7.5','country_lng' => '134.5','timezone' => 'Pacific/Palau'),
    		array('id' => '168','sortname' => 'PS','country_name' => 'Palestinian Territory Occupied','country_lat' => '31.9','country_lng' => '35.2','timezone' => 'Asia/Gaza'),
    		array('id' => '169','sortname' => 'PA','country_name' => 'Panama','country_lat' => '9','country_lng' => '-80','timezone' => 'America/Panama'),
    		array('id' => '170','sortname' => 'PG','country_name' => 'Papua new Guinea','country_lat' => '-6','country_lng' => '147','timezone' => 'Pacific/Port_Moresby'),
    		array('id' => '171','sortname' => 'PY','country_name' => 'Paraguay','country_lat' => '-23','country_lng' => '-58','timezone' => 'America/Asuncion'),
    		array('id' => '172','sortname' => 'PE','country_name' => 'Peru','country_lat' => '-10','country_lng' => '-76','timezone' => 'America/Lima'),
    		array('id' => '173','sortname' => 'PH','country_name' => 'Philippines','country_lat' => '13','country_lng' => '122','timezone' => 'Asia/Manila'),
    		array('id' => '174','sortname' => 'PN','country_name' => 'Pitcairn Island','country_lat' => '-25.06666666','country_lng' => '-130.1','timezone' => 'Pacific/Pitcairn'),
    		array('id' => '175','sortname' => 'PL','country_name' => 'Poland','country_lat' => '52','country_lng' => '20','timezone' => 'Europe/Warsaw'),
    		array('id' => '176','sortname' => 'PT','country_name' => 'Portugal','country_lat' => '39.5','country_lng' => '-8','timezone' => 'Europe/Lisbon'),
    		array('id' => '177','sortname' => 'PR','country_name' => 'Puerto Rico','country_lat' => '18.25','country_lng' => '-66.5','timezone' => 'America/Puerto_Rico'),
    		array('id' => '178','sortname' => 'QA','country_name' => 'Qatar','country_lat' => '25.5','country_lng' => '51.25','timezone' => 'Asia/Qatar'),
    		array('id' => '179','sortname' => 'RE','country_name' => 'Reunion','country_lat' => '-21.15','country_lng' => '55.5','timezone' => 'Indian/Reunion'),
    		array('id' => '180','sortname' => 'RO','country_name' => 'Romania','country_lat' => '46','country_lng' => '25','timezone' => 'Europe/Bucharest'),
    		array('id' => '181','sortname' => 'RU','country_name' => 'Russia','country_lat' => '60','country_lng' => '100','timezone' => 'Europe/Kaliningrad'),
    		array('id' => '182','sortname' => 'RW','country_name' => 'Rwanda','country_lat' => '-2','country_lng' => '30','timezone' => 'Africa/Kigali'),
    		array('id' => '183','sortname' => 'SH','country_name' => 'Saint Helena','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '184','sortname' => 'KN','country_name' => 'Saint Kitts And Nevis','country_lat' => '17.33333333','country_lng' => '-62.75','timezone' => 'America/St_Kitts'),
    		array('id' => '185','sortname' => 'LC','country_name' => 'Saint Lucia','country_lat' => '13.88333333','country_lng' => '-60.96666666','timezone' => 'America/St_Lucia'),
    		array('id' => '186','sortname' => 'PM','country_name' => 'Saint Pierre and Miquelon','country_lat' => '46.83333333','country_lng' => '-56.33333333','timezone' => 'America/Miquelon'),
    		array('id' => '187','sortname' => 'VC','country_name' => 'Saint Vincent And The Grenadines','country_lat' => '13.25','country_lng' => '-61.2','timezone' => 'America/St_Vincent'),
    		array('id' => '188','sortname' => 'WS','country_name' => 'Samoa','country_lat' => '-13.58333333','country_lng' => '-172.33333333','timezone' => 'Pacific/Apia'),
    		array('id' => '189','sortname' => 'SM','country_name' => 'San Marino','country_lat' => '43.76666666','country_lng' => '12.41666666','timezone' => 'Europe/San_Marino'),
    		array('id' => '190','sortname' => 'ST','country_name' => 'Sao Tome and Principe','country_lat' => '1','country_lng' => '7','timezone' => 'Africa/Sao_Tome'),
    		array('id' => '191','sortname' => 'SA','country_name' => 'Saudi Arabia','country_lat' => '25','country_lng' => '45','timezone' => 'Asia/Riyadh'),
    		array('id' => '192','sortname' => 'SN','country_name' => 'Senegal','country_lat' => '14','country_lng' => '-14','timezone' => 'Africa/Dakar'),
    		array('id' => '193','sortname' => 'RS','country_name' => 'Serbia','country_lat' => '44','country_lng' => '21','timezone' => 'Europe/Belgrade'),
    		array('id' => '194','sortname' => 'SC','country_name' => 'Seychelles','country_lat' => '-4.58333333','country_lng' => '55.66666666','timezone' => 'Indian/Mahe'),
    		array('id' => '195','sortname' => 'SL','country_name' => 'Sierra Leone','country_lat' => '8.5','country_lng' => '-11.5','timezone' => 'Africa/Freetown'),
    		array('id' => '196','sortname' => 'SG','country_name' => 'Singapore','country_lat' => '1.36666666','country_lng' => '103.8','timezone' => 'Asia/Singapore'),
    		array('id' => '197','sortname' => 'SK','country_name' => 'Slovakia','country_lat' => '48.66666666','country_lng' => '19.5','timezone' => 'Europe/Bratislava'),
    		array('id' => '198','sortname' => 'SI','country_name' => 'Slovenia','country_lat' => '46.11666666','country_lng' => '14.81666666','timezone' => 'Europe/Ljubljana'),
    		array('id' => '199','sortname' => 'GB','country_name' => 'Smaller Territories of the UK','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '200','sortname' => 'SB','country_name' => 'Solomon Islands','country_lat' => '-8','country_lng' => '159','timezone' => 'Pacific/Guadalcanal'),
    		array('id' => '201','sortname' => 'SO','country_name' => 'Somalia','country_lat' => '10','country_lng' => '49','timezone' => 'Africa/Mogadishu'),
    		array('id' => '202','sortname' => 'ZA','country_name' => 'South Africa','country_lat' => '-29','country_lng' => '24','timezone' => 'Africa/Johannesburg'),
    		array('id' => '203','sortname' => 'GS','country_name' => 'South Georgia','country_lat' => '-54.5','country_lng' => '-37','timezone' => 'Atlantic/South_Georgia'),
    		array('id' => '204','sortname' => 'SS','country_name' => 'South Sudan','country_lat' => '7','country_lng' => '30','timezone' => 'Africa/Juba'),
    		array('id' => '205','sortname' => 'ES','country_name' => 'Spain','country_lat' => '40','country_lng' => '-4','timezone' => 'Europe/Madrid'),
    		array('id' => '206','sortname' => 'LK','country_name' => 'Sri Lanka','country_lat' => '7','country_lng' => '81','timezone' => 'Asia/Colombo'),
    		array('id' => '207','sortname' => 'SD','country_name' => 'Sudan','country_lat' => '15','country_lng' => '30','timezone' => 'Africa/Khartoum'),
    		array('id' => '208','sortname' => 'SR','country_name' => 'Suriname','country_lat' => '4','country_lng' => '-56','timezone' => 'America/Paramaribo'),
    		array('id' => '209','sortname' => 'SJ','country_name' => 'Svalbard And Jan Mayen Islands','country_lat' => '78','country_lng' => '20','timezone' => 'Arctic/Longyearbyen'),
    		array('id' => '210','sortname' => 'SZ','country_name' => 'Swaziland','country_lat' => '-26.5','country_lng' => '31.5','timezone' => 'Africa/Mbabane'),
    		array('id' => '211','sortname' => 'SE','country_name' => 'Sweden','country_lat' => '62','country_lng' => '15','timezone' => 'Europe/Stockholm'),
    		array('id' => '212','sortname' => 'CH','country_name' => 'Switzerland','country_lat' => '47','country_lng' => '8','timezone' => 'Europe/Zurich'),
    		array('id' => '213','sortname' => 'SY','country_name' => 'Syria','country_lat' => '35','country_lng' => '38','timezone' => 'Asia/Damascus'),
    		array('id' => '214','sortname' => 'TW','country_name' => 'Taiwan','country_lat' => '23.5','country_lng' => '121','timezone' => 'Asia/Taipei'),
    		array('id' => '215','sortname' => 'TJ','country_name' => 'Tajikistan','country_lat' => '39','country_lng' => '71','timezone' => 'Asia/Dushanbe'),
    		array('id' => '216','sortname' => 'TZ','country_name' => 'Tanzania','country_lat' => '-6','country_lng' => '35','timezone' => 'Africa/Dar_es_Salaam'),
    		array('id' => '217','sortname' => 'TH','country_name' => 'Thailand','country_lat' => '15','country_lng' => '100','timezone' => 'Asia/Bangkok'),
    		array('id' => '218','sortname' => 'TG','country_name' => 'Togo','country_lat' => '8','country_lng' => '1.16666666','timezone' => 'Africa/Lome'),
    		array('id' => '219','sortname' => 'TK','country_name' => 'Tokelau','country_lat' => '-9','country_lng' => '-172','timezone' => 'Pacific/Fakaofo'),
    		array('id' => '220','sortname' => 'TO','country_name' => 'Tonga','country_lat' => '-20','country_lng' => '-175','timezone' => 'Pacific/Tongatapu'),
    		array('id' => '221','sortname' => 'TT','country_name' => 'Trinidad And Tobago','country_lat' => '11','country_lng' => '-61','timezone' => 'America/Port_of_Spain'),
    		array('id' => '222','sortname' => 'TN','country_name' => 'Tunisia','country_lat' => '34','country_lng' => '9','timezone' => 'Africa/Tunis'),
    		array('id' => '223','sortname' => 'TR','country_name' => 'Turkey','country_lat' => '39','country_lng' => '35','timezone' => 'Europe/Istanbul'),
    		array('id' => '224','sortname' => 'TM','country_name' => 'Turkmenistan','country_lat' => '40','country_lng' => '60','timezone' => 'Asia/Ashgabat'),
    		array('id' => '225','sortname' => 'TC','country_name' => 'Turks And Caicos Islands','country_lat' => '21.75','country_lng' => '-71.58333333','timezone' => 'America/Grand_Turk'),
    		array('id' => '226','sortname' => 'TV','country_name' => 'Tuvalu','country_lat' => '-8','country_lng' => '178','timezone' => 'Pacific/Funafuti'),
    		array('id' => '227','sortname' => 'UG','country_name' => 'Uganda','country_lat' => '1','country_lng' => '32','timezone' => 'Africa/Kampala'),
    		array('id' => '228','sortname' => 'UA','country_name' => 'Ukraine','country_lat' => '49','country_lng' => '32','timezone' => 'Europe/Kiev'),
    		array('id' => '229','sortname' => 'AE','country_name' => 'United Arab Emirates','country_lat' => '24','country_lng' => '54','timezone' => 'Asia/Dubai'),
    		array('id' => '230','sortname' => 'GB','country_name' => 'United Kingdom','country_lat' => '54','country_lng' => '-2','timezone' => 'Europe/London'),
    		array('id' => '231','sortname' => 'US','country_name' => 'United States','country_lat' => '38','country_lng' => '-97','timezone' => 'America/New_York'),
    		array('id' => '232','sortname' => 'UM','country_name' => 'United States Minor Outlying Islands','country_lat' => '19.2911437','country_lng' => '166.618332','timezone' => 'Pacific/Johnston'),
    		array('id' => '233','sortname' => 'UY','country_name' => 'Uruguay','country_lat' => '-33','country_lng' => '-56','timezone' => 'America/Montevideo'),
    		array('id' => '234','sortname' => 'UZ','country_name' => 'Uzbekistan','country_lat' => '41','country_lng' => '64','timezone' => 'Asia/Samarkand'),
    		array('id' => '235','sortname' => 'VU','country_name' => 'Vanuatu','country_lat' => '-16','country_lng' => '167','timezone' => 'Pacific/Efate'),
    		array('id' => '236','sortname' => 'VA','country_name' => 'Vatican City State (Holy See)','country_lat' => '41.9','country_lng' => '12.45','timezone' => 'Europe/Vatican'),
    		array('id' => '237','sortname' => 'VE','country_name' => 'Venezuela','country_lat' => '8','country_lng' => '-66','timezone' => 'America/Caracas'),
    		array('id' => '238','sortname' => 'VN','country_name' => 'Vietnam','country_lat' => '16.16666666','country_lng' => '107.83333333','timezone' => 'Asia/Ho_Chi_Minh'),
    		array('id' => '239','sortname' => 'VG','country_name' => 'Virgin Islands (British)','country_lat' => '18.431383','country_lng' => '-64.62305','timezone' => 'America/Tortola'),
    		array('id' => '240','sortname' => 'VI','country_name' => 'Virgin Islands (US)','country_lat' => '18.35','country_lng' => '-64.933333','timezone' => 'America/St_Thomas'),
    		array('id' => '241','sortname' => 'WF','country_name' => 'Wallis And Futuna Islands','country_lat' => '-13.3','country_lng' => '-176.2','timezone' => 'Pacific/Wallis'),
    		array('id' => '242','sortname' => 'EH','country_name' => 'Western Sahara','country_lat' => '24.5','country_lng' => '-13','timezone' => 'Africa/El_Aaiun'),
    		array('id' => '243','sortname' => 'YE','country_name' => 'Yemen','country_lat' => '15','country_lng' => '48','timezone' => 'Asia/Aden'),
    		array('id' => '244','sortname' => 'YU','country_name' => 'Yugoslavia','country_lat' => '','country_lng' => '','timezone' => ''),
    		array('id' => '245','sortname' => 'ZM','country_name' => 'Zambia','country_lat' => '-15','country_lng' => '30','timezone' => 'Africa/Lusaka'),
    		array('id' => '246','sortname' => 'ZW','country_name' => 'Zimbabwe','country_lat' => '-20','country_lng' => '30','timezone' => 'Africa/Harare')
    	];
    	DB::table('countries')->insert($Countries);
    }
}
