version: 0.2
phases:
   install:
     runtime-versions:
         php: 7.3
         nodejs: 12.x
     commands:
         - yum update -y
         - yum install -y amazon-linux-extras php7.3
         - yum install -y php-curl php-mbstring php-intl php-opcache php-soap php-gd php-xml php-mysqli
         - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
         - yum install -y libsodium-devel.x86_64
   pre_build:
     commands:
         - composer install
         - npm install
   build:
     commands:
         - npm run production
         - php artisan migrate --force
         - php artisan db:seed
artifacts:
   files:
         - '**/*'
   name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
   upload-artifacts: yes
   logs: yes